---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default:
    desc: List tasks
    silent: true
    cmds:
      - task -t tasks/ansible.yml --list

  init:
    desc: Initialize Ansible
    silent: true
    sources:
      - ansible/requirements.yml
    cmds:
      - ansible-galaxy install -r ansible/requirements.yml

  apply:
    desc: Apply Ansible playbooks
    silent: true
    deps:
      - init
    sources:
      - ansible/**/*.yml
      - ansible/**/*.j2
    cmds:
      - sops exec-file --output-type json secrets.yml "scripts/ansible/apply.sh {}"

  test:
    desc: Test Ansible playbooks syntax
    silent: true
    deps:
      - init
    sources:
      - ansible/**/*.yml
      - ansible/**/*.j2
    cmds:
      - scripts/ansible/test.sh

  ping:
    desc: Ping all Ansible hosts
    silent: true
    cmds:
      - scripts/ansible/ping.sh
