---
minecraft_version: latest
minecraft_motd: Hello, World!
minecraft_difficulty: normal
minecraft_whitelist_file: ""
minecraft_icon: ""
minecraft_enable_query: "TRUE"
minecraft_seed: "-123456792079414942"
minecraft_game_mode: survival
