---
- name: Create volume for Minecraft
  docker_volume:
    name: minecraft
    state: present

- name: Deploy Minecraft server
  docker_container:
    name: minecraft
    image: itzg/minecraft-server:latest
    state: started
    recreate: true
    restart_policy: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - minecraft:/data
    env:
      VERSION: "{{ minecraft_version }}"
      EULA: "TRUE"
      MOTD: "{{ minecraft_motd }}"
      DIFFICULTY: "{{ minecraft_difficulty }}"
      WHITELIST_FILE: "{{ minecraft_whitelist_file }}"
      EXISTING_WHITELIST_FILE: "SYNCHRONIZE"
      ICON: "{{ minecraft_icon }}"
      ENABLE_QUERY: "{{ minecraft_enable_query }}"
      SEED: "{{ minecraft_seed }}"
      MODE: "{{ minecraft_game_mode }}"
