---
- name: Common setup
  hosts: all
  become: true
  roles:
    - common

- name: Java setup
  hosts: all
  become: true
  roles:
    - java

- name: Minecraft setup
  hosts: all
  become: true
  roles:
    - minecraft
